import { __rest } from "tslib";
import { jsx as _jsx } from "react/jsx-runtime";
import clsx from "clsx";
const roundnessMap = {
    none: "rounded-none",
    xs: "rounded-xs",
    sm: "rounded-sm",
    md: "rounded-md",
    lg: "rounded-lg",
    xl: "rounded-xl",
    "2xl": "rounded-2xl",
    "3xl": "rounded-3xl",
    "4xl": "rounded-4xl",
    full: "rounded-full",
    // directional
    "top-xs": "rounded-t-xs",
    "top-sm": "rounded-t-sm",
    "top-md": "rounded-t-md",
    "top-lg": "rounded-t-lg",
    "top-xl": "rounded-t-xl",
    "top-2xl": "rounded-t-2xl",
    "top-3xl": "rounded-t-3xl",
    "top-4xl": "rounded-t-4xl",
    "right-xs": "rounded-r-xs",
    "right-sm": "rounded-r-sm",
    "right-md": "rounded-r-md",
    "right-lg": "rounded-r-lg",
    "right-xl": "rounded-r-xl",
    "right-2xl": "rounded-r-2xl",
    "right-3xl": "rounded-r-3xl",
    "right-4xl": "rounded-r-4xl",
    "bottom-xs": "rounded-b-xs",
    "bottom-sm": "rounded-b-sm",
    "bottom-md": "rounded-b-md",
    "bottom-lg": "rounded-b-lg",
    "bottom-xl": "rounded-b-xl",
    "bottom-2xl": "rounded-b-2xl",
    "bottom-3xl": "rounded-b-3xl",
    "bottom-4xl": "rounded-b-4xl",
    "left-xs": "rounded-l-xs",
    "left-sm": "rounded-l-sm",
    "left-md": "rounded-l-md",
    "left-lg": "rounded-l-lg",
    "left-xl": "rounded-l-xl",
    "left-2xl": "rounded-l-2xl",
    "left-3xl": "rounded-l-3xl",
    "left-4xl": "rounded-l-4xl",
    "x-xs": "rounded-s-xs",
    "x-sm": "rounded-s-sm",
    "x-md": "rounded-s-md",
    "x-lg": "rounded-s-lg",
    "x-xl": "rounded-s-xl",
    "x-2xl": "rounded-s-2xl",
    "x-3xl": "rounded-s-3xl",
    "x-4xl": "rounded-s-4xl",
    "y-xs": "rounded-e-xs",
    "y-sm": "rounded-e-sm",
    "y-md": "rounded-e-md",
    "y-lg": "rounded-e-lg",
    "y-xl": "rounded-e-xl",
    "y-2xl": "rounded-e-2xl",
    "y-3xl": "rounded-e-3xl",
    "y-4xl": "rounded-e-4xl",
    "tr-xs": "rounded-tr-xs",
    "tr-sm": "rounded-tr-sm",
    "tr-md": "rounded-tr-md",
    "tr-lg": "rounded-tr-lg",
    "tr-xl": "rounded-tr-xl",
    "tr-2xl": "rounded-tr-2xl",
    "tr-3xl": "rounded-tr-3xl",
    "tr-4xl": "rounded-tr-4xl",
    "br-xs": "rounded-br-xs",
    "br-sm": "rounded-br-sm",
    "br-md": "rounded-br-md",
    "br-lg": "rounded-br-lg",
    "br-xl": "rounded-br-xl",
    "br-2xl": "rounded-br-2xl",
    "br-3xl": "rounded-br-3xl",
    "br-4xl": "rounded-br-4xl",
    "tl-xs": "rounded-tl-xs",
    "tl-sm": "rounded-tl-sm",
    "tl-md": "rounded-tl-md",
    "tl-lg": "rounded-tl-lg",
    "tl-xl": "rounded-tl-xl",
    "tl-2xl": "rounded-tl-2xl",
    "tl-3xl": "rounded-tl-3xl",
    "tl-4xl": "rounded-tl-4xl",
    "bl-xs": "rounded-bl-xs",
    "bl-sm": "rounded-bl-sm",
    "bl-md": "rounded-bl-md",
    "bl-lg": "rounded-bl-lg",
    "bl-xl": "rounded-bl-xl",
    "bl-2xl": "rounded-bl-2xl",
    "bl-3xl": "rounded-bl-3xl",
    "bl-4xl": "rounded-bl-4xl",
};
const sizeMap = {
    xs: "text-xs py-1 px-2",
    sm: "text-sm py-1.5 px-3",
    md: "text-base py-2 px-4",
    lg: "text-lg py-2.5 px-5",
    xl: "text-xl py-3 px-6",
    xxl: "text-2xl py-4 px-8",
    xxxl: "text-3xl py-5 px-10",
    xxxxl: "text-4xl py-6 px-12",
};
const Button = (_a) => {
    var { variant = "normal", bgcolor = "primary", text = "light", size = "md", fullWidth = false, roundness = "md", disabled = false, className = "", children = "Button" } = _a, props = __rest(_a, ["variant", "bgcolor", "text", "size", "fullWidth", "roundness", "disabled", "className", "children"]);
    const base = "inline-flex items-center justify-center font-medium focus:outline-none transition-all";
    const variantClass = variant === "outline"
        ? `border border-${bgcolor} bg-transparent text-${bgcolor}`
        : `bg-${bgcolor} text-${text}`;
    const finalClassName = clsx(base, sizeMap[size], variantClass, roundnessMap[roundness], fullWidth ? "w-full" : "w-auto", className);
    return (_jsx("button", Object.assign({ className: finalClassName, disabled: disabled }, props, { children: children })));
};
export default Button;
//# sourceMappingURL=Button.js.map